steps:
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'client'
    entrypoint: 'npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'client'
    entrypoint: 'npm'
    args: ['run', 'build']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'client'
    entrypoint: 'gcloud'
    args: 
      - 'app'
      - 'deploy'
      - 'app.yaml'
      - '--project'
      - 'centered-oasis-418917'
      - '--quiet'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

# steps:
#     - name: 'gcr.io/cloud-builders/docker'
#       directory : 'client'
#       args:['build', '-t', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA']

#     - name: 'gcr.io/cloud-builders/docker'
#       args:['push', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA']

#     - name: 'gcr.io/cloud-builders/gcloud'
#     args: ['run', 'deploy', '', '--image', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA', '--platform=managed', '--region=<your service region>']
    



