steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
    dir: 'server'
    args: ['install']
- name: 'gcr.io/cloud-builders/npm'
    dir: 'server'
    args: ['run', 'test']
# Build
- name: 'gcr.io/cloud-builders/npm'
  dir: 'server'
  args: ['run', 'build']
# Deploy
- name: 'gcr.io/cloud-builders/npm'
  dir: 'server'
  args: ['deploy']


# - name: 'gcr.io/cloud-builders/npm'
#     dir: 'client'
#     args: ['install']
# - name: 'gcr.io/cloud-builders/npm'
#     dir: 'client'
#     args: ['run', 'test']
# # Build
# - name: 'gcr.io/cloud-builders/npm'
#   dir: 'client'
#   args: ['run', 'build']
# # Deploy
# - name: 'gcr.io/cloud-builders/npm'
#   dir: 'client'
#   args: ['deploy']



