steps:
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'client'
    entrypoint: 'npm'
    args: ['install']
  # - name: 'gcr.io/cloud-builders/npm'
  #   dir: 'client'
  #   entrypoint: 'npm'
  #   env : 
  #     - 'CI=true'
  #   args: ['run', 'test']
  # Build
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'client'
    entrypoint: 'npm'
    args: ['run', 'build']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'client'
    entrypoint: 'gcloud'
    args: 
      - 'app'
      - 'deploy'
      - 'app.yaml'
      - '--project'
      - 'centered-oasis-418917'
      - '--quiet'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET



