steps:
#   # Install dependencies
#   - name: 'gcr.io/cloud-builders/npm'
#     dir: 'server'
#     entrypoint: 'npm'
#     args: ['install']

#   # Run tests
#   # - name: 'gcr.io/cloud-builders/npm'
#   #   dir: 'server'
#   #   entrypoint: 'npm'
#   #   args: ['run', 'test']

#   # Build the application
#   - name: 'gcr.io/cloud-builders/npm'
#     dir: 'server'
#     entrypoint: 'npm'
#     args: ['run', 'build']

#   # Deploy to Google App Engine
#   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     dir: 'server'
#     entrypoint: 'gcloud'
#     args: 
#       - 'app'
#       - 'deploy'
#       - 'app.yaml'
#       - '--project'
#       - 'centered-oasis-418917'
#       - '--quiet'
# options:
#   defaultLogsBucketBehavior : REGIONAL_USER_OWNED_BUCKET
# timeout: '1600s'  # Optional, adjust based on expected build times


- name: 'gcr.io/cloud-builders/npm'
    dir: 'client'
    entrypoint: 'npm'
    args: ['install']
- name: 'gcr.io/cloud-builders/npm'
    dir: 'client'
    entrypoint: 'npm'
    args: ['run', 'test']
# Build
- name: 'gcr.io/cloud-builders/npm'
  dir: 'client'
  entrypoint: 'npm'
  args: ['run', 'build']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'client'
    entrypoint: 'gcloud'
    args: 
      - 'app'
      - 'deploy'
      - 'app.yaml'
      - '--project'
      - 'centered-oasis-418917'
      - '--quiet'

options:
logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior : REGIONAL_USER_OWNED_BUCKET


