steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'server'
    entrypoint: 'npm'
    args: ['install']

  # Run tests
  # - name: 'gcr.io/cloud-builders/npm'
  #   dir: 'server'
  #   entrypoint: 'npm'
  #   args: ['run', 'test']

  # Build the application
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'server'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Deploy to Google App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'server'
    entrypoint: 'gcloud'
    args: 
      - 'app'
      - 'deploy'
      - 'app.yaml'
      - '--project'
      - 'centered-oasis-418917'
      - '--quiet'
options:
  defaultLogsBucketBehavior : REGIONAL_USER_OWNED_BUCKET
# timeout: '1600s'  # Optional, adjust based on expected build times


# - name: 'node'
#     dir: 'client'
#     args: ['install']
# - name: 'node'
#     dir: 'client'
#     args: ['run', 'test']
# # Build
# - name: 'node'
#   dir: 'client'
#   args: ['run', 'build']
# # Deploy
# - name: 'node'
#   dir: 'client'
#   args: ['deploy']



