steps:
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'server'
    entrypoint: 'npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    dir: 'server'
    entrypoint: 'npm'
    args: ["run", "create-env"]
    env:
      - 'MONGO_URL=${_MONGO_URL}'
      - 'ACCESS_TOKEN_SECRET=${_ACCESS_TOKEN_SECRET}'
      - 'MONGO_PASSWORD=${_MONGO_PASSWORD}'
      - 'MONGO_USERNAME=${_MONGO_USERNAME}'
      - 'EMAIL=${_EMAIL}'
      - 'PASS=${_PASS}'
      - 'COOKIE_DOMAIN=${_COOKIE_DOMAIN}'
      - 'STRIPE_PRIVATE_KEY=${_STRIPE_PRIVATE_KEY}'
      - 'STRIPE_PUBLIC_KEY=${_STRIPE_PUBLIC_KEY}'
      - 'STRIPE_ENDPOINT_SECRET=${_STRIPE_ENDPOINT_SECRET}'
      - 'CLIENT_URL=${_CLIENT_URL}'
      - 'GOOGLE_OAUTH_CLIENT_ID_SIGNIN=${_GOOGLE_OAUTH_CLIENT_ID_SIGNIN}'
      - 'GOOGLE_OAUTH_TYPE=${_GOOGLE_OAUTH_TYPE}'
      - 'GOOGLE_OAUTH_PROJECT_ID=${_GOOGLE_OAUTH_PROJECT_ID}'
      - 'GOOGLE_OAUTH_PRIVATE_KEY_ID=${_GOOGLE_OAUTH_PRIVATE_KEY_ID}'
      - 'GOOGLE_OAUTH_PRIVATE_KEY=${_GOOGLE_OAUTH_PRIVATE_KEY}'
      - 'GOOGLE_OAUTH_CLIENT_EMAIL=${_GOOGLE_OAUTH_CLIENT_EMAIL}'
      - 'GOOGLE_OAUTH_CLIENT_ID=${_GOOGLE_OAUTH_CLIENT_ID}'
      - 'GOOGLE_OAUTH_AUTH_URI=${_GOOGLE_OAUTH_AUTH_URI}'
      - 'GOOGLE_OAUTH_TOKEN_URI=${_GOOGLE_OAUTH_TOKEN_URI}'
      - 'GOOGLE_OAUTH_AUTH_PROVIDER_X509_CERT_URL=${_GOOGLE_OAUTH_AUTH_PROVIDER_X509_CERT_URL}'
      - 'GOOGLE_OAUTH_CLIENT_X509_CERT_URL=${_GOOGLE_OAUTH_CLIENT_X509_CERT_URL}'
      - 'GOOGLE_OAUTH_UNIVERSE_DOMAIN=${_GOOGLE_OAUTH_UNIVERSE_DOMAIN}'

  - name: "gcr.io/cloud-builders/gcloud"
    dir: 'server'
    args: 
      - 'app'
      - 'deploy'
      - 'app.yaml'
      - '--project'
      - 'centered-oasis-418917'
      - '--quiet'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

timeout: "1600s"
